SELECT ?attributeUri ?attribute (GROUP_CONCAT(DISTINCT(COALESCE(?label, ?value)) ; separator=", ") as ?values)
FROM <${params.graph}>
FROM <${wikinormia}>
WHERE {
    <${params.uri}> wkn:isoxmlTSK\#D ?farm.
    ?farm ?attributeUri ?value.
    OPTIONAL { ?value rdfs:label ?label }
    ?attributeUri rdfs:domain wkn:isoxmlFRM ;
                  rdfs:label ?attribute.
}
GROUP BY ?attributeUri ?attribute
ORDER BY ?attribute
