SELECT  *
WHERE
{ GRAPH <${graph}> { 
  
  
    ?o  ?p  <${uri}>
              
              OPTIONAL
              { ?o  rdfs:label  ?o_label }
              OPTIONAL
              { ?o  rdf:type  ?o_type . 
               
                 GRAPH <https://app.sdsd-projekt.de/wikinormia/>
                     { 
                       ?o_type a rdfs:Class .
                       OPTIONAL
                       { ?o_type  rdfs:label  ?o_type_label }
                     }
              }
              
              OPTIONAL {
                GRAPH <https://app.sdsd-projekt.de/wikinormia/>
                      { 
                        ?p a rdf:Property .
                        OPTIONAL
                        { ?p  rdfs:label  ?p_label }
                      }
                      
              }
        }
}
order by desc(?p)
