select *
{
    graph <${graph}> {
        <${uri}> ?p ?o .
        optional {
            <${uri}> rdfs:comment ?comment .
        }
        filter(isLiteral(?o) && strlen(str(?o)) > 0)
    }

    graph <https://app.sdsd-projekt.de/wikinormia/> {
        ?p a rdf:Property .
        optional {
            ?p rdfs:label ?p_label .
        }
    }
}
order by strlen(str(?o))
